//
//  PlayerAid
//

extern BOOL DEBUG_MODE_FLOW_EDIT_TUTORIAL;
extern BOOL DEBUG_MODE_FLOW_PUBLISH_TUTORIAL;
extern BOOL DEBUG_MODE_ADD_TUTORIAL_STEPS;
extern BOOL DEBUG_MODE_ADD_PHOTO;
extern BOOL DEBUG_OFFLINE_MODE;