//
//  PlayerAid
//

#import "DebugSettings.h"

/**
 REMEMBER TO DISABLE THIS FOR PREPARING A BUILD AS THIS DRIVES THE APP FLOW AUTOMATICALLY!!
 */
BOOL DEBUG_MODE_FLOW_EDIT_TUTORIAL = NO;
BOOL DEBUG_MODE_FLOW_PUBLISH_TUTORIAL = NO;
BOOL DEBUG_MODE_ADD_TUTORIAL_STEPS = YES;