
@import UIKit;

extern const CGFloat kKeyboardMakeCommentAccessoryInputViewHeight;
extern const CGFloat kKeyboardEditCommentAccessoryInputViewHeight;
extern const CGFloat kKeyboardGuideTextStepAccessoryInputViewHeight;
